name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v1

      - name: Build with Gradle
        run: ./gradlew generatePatchesFiles clean --parallel

  node:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: 'npm'

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.REPOSITORY_PUSH_ACCESS }}
        run: npm exec semantic-release

  trigger-apk-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger APK Build
        run: |
          curl -X POST https://api.github.com/repos/crimera/piko-builds/dispatches \
          -H 'Accept: application/vnd.github+json' \
          -H "Authorization: Bearer ${{secrets.ACCESS_TOKEN}}" \
          -d '{"event_type": "build"}'
